sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
before_install:
  - gem update --system --no-doc
  - bundle install --gemfile=.overcommit_gems.rb
before_script:
  - git config --global user.email 'travis@travis.ci'
  - git config --global user.name 'Travis CI'
script:
  - bundle exec rspec
  - overcommit --sign
  - overcommit --run
