sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
before_install:
  - gem update --system --no-doc
  - bundle install --gemfile=.overcommit_gems.rb
script:
  - bundle exec rspec
  - overcommit --sign
  - overcommit --run
